resolve dev to fitchRoute.
krasyukden/marvel-project02 pull request #2
Opened 2021-12-08 13:34 UTC by krasyukden

2021-12-10 12:53 UTC, alinalaktionova requested changes

2021-12-10 12:53 UTC, alinalaktionova commented on src/ComicsPage.module.css
> +	margin: 0;
tabs

2021-12-10 12:53 UTC, alinalaktionova commented on src/ComicsPage.tsx
> +  comics: any[],
remove any

2021-12-10 12:53 UTC, alinalaktionova commented on src/ComicsPage.tsx
> +        const characterId = this.props?.match?.params?.charachterId;
again tab

2021-12-10 12:53 UTC, alinalaktionova commented on src/ComicsPage.tsx
> +     return <>{ }
????

2021-12-10 12:53 UTC, alinalaktionova commented on src/ComicsPage.tsx
> +      <div className={styles.wrapper}>
use destructuring

2021-12-10 12:53 UTC, alinalaktionova commented on src/ComicsPage.tsx
> +          {this.state.comics.slice(0, 5).map(comics => {
why do you need slice?

2021-12-10 12:53 UTC, alinalaktionova commented on src/ComicsPage.tsx
> +              <img className={styles.heroesImg} src={comics.thumbnail.path != null
use strict equality

2021-12-10 12:53 UTC, alinalaktionova commented on src/ComicsPage.tsx
> +                ? `${comics.thumbnail.path}.${comics.thumbnail.extension}` : 'Photo'} />
again destructuring is better here

2021-12-10 12:53 UTC, alinalaktionova commented on src/HomePage.module.css
> +	margin: 0;
code style

2021-12-10 12:53 UTC, alinalaktionova commented on src/ComicsPage.module.css
> +*{
better to name file comics_page.style.css

2021-12-10 12:53 UTC, alinalaktionova commented on src/HomePage.tsx
> +  heroes: any[],
any

2021-12-10 12:53 UTC, alinalaktionova commented on src/HomePage.tsx
> +interface HomeProps {
why HomeState and HomeProps has the same properties? And what means 'Home'?

2021-12-10 12:53 UTC, alinalaktionova commented on src/HomePage.tsx
> +
empty line for what?

2021-12-10 12:53 UTC, alinalaktionova commented on src/HomePage.tsx
> +  loadFromServer() {
method name should be clear and describes what you really do

2021-12-10 12:53 UTC, alinalaktionova commented on src/HomePage.tsx
> +                  <NavLink to={`/comics/${heroes.id}`} style={{ textDecoration: 'none' }}> {<Button variant="contained"
choose 1 way of setting styles either inline or separate css files

2021-12-10 12:53 UTC, alinalaktionova commented on src/HomePage.tsx
> +                  <NavLink to={`/comics/${heroes.id}`} style={{ textDecoration: 'none' }}> {<Button variant="contained"
what's wrong with code style? linter should fix all this problems

2021-12-10 12:53 UTC, alinalaktionova commented on src/NotFoundPage.tsx
> +
what is this?

2021-12-10 12:53 UTC, alinalaktionova commented on src/api.js
> +  hash: hash
no need to duplicate property with the same name

2021-12-10 12:53 UTC, alinalaktionova commented on src/api.js
> +  return axios.get(`${baseURL}characters/${characterId}/comics?ts=1&apikey=${PUBLIC_KEY}&hash=${hash}`)
use params in axios for query

2021-12-10 12:53 UTC, alinalaktionova commented on src/api.js
> +      const res = response.data.data.results;
no need to create separate var for res

2021-12-10 12:53 UTC, alinalaktionova commented on src/api.js
> +  return axios.get(`${baseURL}characters?nameStartsWith=${nameStartsWith}&`, {params})
nameStartsWith can be in params object

2021-12-10 12:53 UTC, alinalaktionova commented on src/assets/Spinner-1s-200px.svg
> +<?xml version="1.0" encoding="utf-8"?>
you can just use library for spinner component))

2021-12-12 13:07 UTC, krasyukden commented on src/api.js
> +  return axios.get(`${baseURL}characters?nameStartsWith=${nameStartsWith}&`, {params})
can I leave it like this, because nameStartsWith comes in parameters?

2021-12-12 15:44 UTC, krasyukden commented on src/assets/Spinner-1s-200px.svg
> +<?xml version="1.0" encoding="utf-8"?>
spinner was changed from MUI

2021-12-13 10:30 UTC, alinalaktionova requested changes
in general good, fix other remarks please

2021-12-13 10:30 UTC, alinalaktionova commented on src/ComicsPage.module.css
>  	padding: 0;
padding also should have 2 spacing tab))

2021-12-13 10:30 UTC, alinalaktionova commented on src/ComicsPage.module.css
>  	padding: 0;
and rename files please, there is a convention to name files from lowercase letter except react component files

2021-12-20 12:25 UTC, alinalaktionova approved these changes

2021-12-21 13:38 UTC, merged